"""
Mock signals for dashboard development.
Mirrors the shape of real data — enrichment fields are None where not yet available.
"""
from __future__ import annotations

import numpy as np
import pandas as pd


def make_df_for(seed: int, n: int = 300) -> pd.DataFrame:
    """Synthetic OHLCV DataFrame for chart generation."""
    rng = np.random.default_rng(seed)
    dates = pd.bdate_range(end="2026-05-23", periods=n)

    price = 50.0
    closes = []
    for i in range(n):
        volatility = 0.008 if i >= n - 30 else 0.018
        drift = 0.0 if i >= n - 30 else 0.0006
        price = max(price * (1 + rng.normal(drift, volatility)), 1.0)
        closes.append(price)

    closes = np.array(closes)
    highs  = closes * (1 + rng.uniform(0.003, 0.015, n))
    lows   = closes * (1 - rng.uniform(0.003, 0.015, n))
    opens  = np.clip(closes * (1 + rng.normal(0, 0.005, n)), lows, highs)
    volume = rng.uniform(300_000, 700_000, n)
    volume[-30:] *= rng.uniform(0.4, 0.7, 30)

    return pd.DataFrame(
        {"open": opens, "high": highs, "low": lows, "close": closes, "volume": volume},
        index=dates,
    )


def _scale(df: pd.DataFrame, base_price: float) -> pd.DataFrame:
    """Scale a synthetic df so the last close matches base_price."""
    factor = base_price / df["close"].iloc[-1]
    for col in ["open", "high", "low", "close"]:
        df[col] = df[col] * factor
    return df


MOCK_SIGNALS: list[dict] = [
    {
        "symbol": "NOVO B",
        "exchange": "CPH",
        "currency": "DKK",
        "composite_score": 85.0,
        "alert_type": "VCP Setup + Pocket Pivot",
        "strategies_fired": ["vcp", "pocket_pivot"],
        "pivot_price": 876.0,
        "signals": {
            "vcp": {
                "strategy": "vcp",
                "pivot_price": 876.0,
                "n_contractions": 3,
                "contraction_depths": [0.11, 0.07, 0.04],
                "volume_declining": True,
                "quality_score": 80.0,
            },
            "pocket_pivot": {
                "strategy": "pocket_pivot",
                "reference_sma": "sma_10",
                "reference_sma_value": 851.0,
                "crosses_over": True,
                "volume_ratio_vs_down_days": 1.9,
                "max_down_day_volume": 420_000,
                "today_volume": 798_000,
                "quality_score": 82.0,
            },
        },
        "entry_price": 876.0,
        "stop_price": 838.0,
        "target_price": 965.0,
        "risk_reward": 2.3,
        "rs_rank": 91.0,
        "eps_qoq": 0.34,
        "eps_yoy": 0.45,
        "revenue_qoq": 0.28,
        "revenue_yoy": 0.32,
        "sales_qoq": 0.25,
        "earnings_days_out": 28,
        "wsb_mentions": 142,
        "daytrading_mentions": 38,
        "insider_buy_days_ago": 12,
        "news_sentiment": 0.72,
        "google_trends_chg": 0.41,
        "pattern_notes": "3 contractions · Vol declining · Near 52w high",
        "_seed": 42,
        "_price": 865.0,
        "_trends_keyword": "Novo Nordisk",
    },
    {
        "symbol": "AAPL",
        "exchange": "NASDAQ",
        "currency": "USD",
        "composite_score": 78.0,
        "alert_type": "VCP Setup",
        "strategies_fired": ["vcp"],
        "pivot_price": 198.5,
        "signals": {
            "vcp": {
                "strategy": "vcp",
                "pivot_price": 198.5,
                "n_contractions": 2,
                "contraction_depths": [0.09, 0.05],
                "volume_declining": True,
                "quality_score": 78.0,
            },
        },
        "entry_price": 198.5,
        "stop_price": 188.0,
        "target_price": 224.0,
        "risk_reward": 2.4,
        "rs_rank": 82.0,
        "eps_qoq": 0.18,
        "eps_yoy": 0.22,
        "revenue_qoq": 0.07,
        "revenue_yoy": 0.12,
        "sales_qoq": None,
        "earnings_days_out": 44,
        "wsb_mentions": 891,
        "daytrading_mentions": 214,
        "insider_buy_days_ago": None,
        "news_sentiment": 0.31,
        "google_trends_chg": 0.12,
        "pattern_notes": "2 contractions · Vol declining · 8-week base",
        "_seed": 7,
        "_price": 196.0,
        "_trends_keyword": "Apple stock",
    },
    {
        "symbol": "VOLV B",
        "exchange": "STO",
        "currency": "SEK",
        "composite_score": 72.0,
        "alert_type": "Qullamaggie Setup",
        "strategies_fired": ["qullamaggie"],
        "pivot_price": 232.0,
        "signals": {
            "qullamaggie": {
                "strategy": "qullamaggie",
                "pivot_price": 232.0,
                "base_low": 211.0,
                "base_days": 17,
                "prior_move_pct": 0.52,
                "volume_drying": True,
                "quality_score": 72.0,
            },
        },
        "entry_price": 232.0,
        "stop_price": 211.0,
        "target_price": 278.0,
        "risk_reward": 2.2,
        "rs_rank": 76.0,
        "eps_qoq": 0.22,
        "eps_yoy": 0.31,
        "revenue_qoq": 0.14,
        "revenue_yoy": 0.19,
        "sales_qoq": 0.17,
        "earnings_days_out": 61,
        "wsb_mentions": None,
        "daytrading_mentions": None,
        "insider_buy_days_ago": 8,
        "news_sentiment": 0.45,
        "google_trends_chg": 0.08,
        "pattern_notes": "17-day base · +52% prior move · Vol dry · Near 10/20 SMA",
        "_seed": 13,
        "_price": 228.0,
        "_trends_keyword": "Volvo",
    },
    {
        "symbol": "MSFT",
        "exchange": "NASDAQ",
        "currency": "USD",
        "composite_score": 68.0,
        "alert_type": "5 EMA Pullback",
        "strategies_fired": ["ema_pullback"],
        "pivot_price": 424.8,
        "signals": {
            "ema_pullback": {
                "strategy": "ema_pullback",
                "entry_trigger": 424.8,
                "inside_day_high": 424.8,
                "inside_day_low": 418.2,
                "surge_move_pct": 0.09,
                "surge_days": 4,
                "surge_volume_ratio": 1.7,
                "days_since_surge": 3,
                "quality_score": 68.0,
            },
        },
        "entry_price": 424.8,
        "stop_price": 412.0,
        "target_price": 452.0,
        "risk_reward": 2.1,
        "rs_rank": 71.0,
        "eps_qoq": 0.21,
        "eps_yoy": 0.19,
        "revenue_qoq": 0.16,
        "revenue_yoy": 0.21,
        "sales_qoq": None,
        "earnings_days_out": 38,
        "wsb_mentions": 327,
        "daytrading_mentions": 88,
        "insider_buy_days_ago": None,
        "news_sentiment": 0.58,
        "google_trends_chg": 0.22,
        "pattern_notes": "4-day surge +9% · Pulled back to 5 EMA · Inside day",
        "_seed": 19,
        "_price": 421.0,
        "_trends_keyword": "Microsoft stock",
    },
    {
        "symbol": "NDA SE",
        "exchange": "STO",
        "currency": "SEK",
        "composite_score": 63.0,
        "alert_type": "Pocket Pivot",
        "strategies_fired": ["pocket_pivot"],
        "pivot_price": 118.4,
        "signals": {
            "pocket_pivot": {
                "strategy": "pocket_pivot",
                "reference_sma": "sma_21",
                "reference_sma_value": 115.2,
                "crosses_over": False,
                "volume_ratio_vs_down_days": 1.5,
                "max_down_day_volume": 310_000,
                "today_volume": 465_000,
                "quality_score": 63.0,
            },
        },
        "entry_price": 118.4,
        "stop_price": 112.0,
        "target_price": 131.0,
        "risk_reward": 2.0,
        "rs_rank": 64.0,
        "eps_qoq": None,
        "eps_yoy": None,
        "revenue_qoq": 0.08,
        "revenue_yoy": 0.11,
        "sales_qoq": None,
        "earnings_days_out": None,
        "wsb_mentions": None,
        "daytrading_mentions": None,
        "insider_buy_days_ago": None,
        "news_sentiment": 0.18,
        "google_trends_chg": None,
        "pattern_notes": "Extends from EMA 21 · Vol ×1.5 vs down days",
        "_seed": 31,
        "_price": 116.0,
        "_trends_keyword": "Nordea bank",
    },
    {
        "symbol": "INVE B",
        "exchange": "STO",
        "currency": "SEK",
        "composite_score": 61.0,
        "alert_type": "Buyable Gap Up",
        "strategies_fired": ["gap_up"],
        "pivot_price": 248.0,
        "signals": {
            "gap_up": {
                "strategy": "gap_up",
                "gap_pct": 0.042,
                "volume_ratio": 2.3,
                "gap_day_low": 238.5,
                "gap_day_high": 248.0,
                "quality_score": 61.0,
            },
        },
        "entry_price": 245.0,
        "stop_price": 238.5,
        "target_price": 268.0,
        "risk_reward": 3.5,
        "rs_rank": 69.0,
        "eps_qoq": 0.12,
        "eps_yoy": 0.18,
        "revenue_qoq": None,
        "revenue_yoy": None,
        "sales_qoq": None,
        "earnings_days_out": 72,
        "wsb_mentions": None,
        "daytrading_mentions": None,
        "insider_buy_days_ago": 3,
        "news_sentiment": 0.61,
        "google_trends_chg": 0.28,
        "pattern_notes": "Gap +4.2% · Vol ×2.3 · Close upper half of range",
        "_seed": 37,
        "_price": 243.0,
        "_trends_keyword": "Investor AB",
    },
    {
        "symbol": "NVDA",
        "exchange": "NASDAQ",
        "currency": "USD",
        "composite_score": 76.0,
        "alert_type": "Qullamaggie Setup",
        "strategies_fired": ["qullamaggie"],
        "pivot_price": 138.5,
        "signals": {
            "qullamaggie": {
                "strategy": "qullamaggie",
                "pivot_price": 138.5,
                "base_low": 121.0,
                "base_days": 14,
                "prior_move_pct": 0.68,
                "volume_drying": True,
                "quality_score": 76.0,
            },
        },
        "entry_price": 138.5,
        "stop_price": 121.0,
        "target_price": 174.0,
        "risk_reward": 2.1,
        "rs_rank": 87.0,
        "eps_qoq": 0.69,
        "eps_yoy": 1.22,
        "revenue_qoq": 0.52,
        "revenue_yoy": 0.78,
        "sales_qoq": 0.49,
        "earnings_days_out": 52,
        "wsb_mentions": 2841,
        "daytrading_mentions": 612,
        "insider_buy_days_ago": None,
        "news_sentiment": 0.81,
        "google_trends_chg": 0.64,
        "pattern_notes": "14-day base · +68% prior move · Vol dry · Near 10/20 SMA",
        "_seed": 53,
        "_price": 135.0,
        "_trends_keyword": "Nvidia stock",
    },
    {
        "symbol": "ERIC B",
        "exchange": "STO",
        "currency": "SEK",
        "composite_score": 64.0,
        "alert_type": "5 EMA Pullback",
        "strategies_fired": ["ema_pullback"],
        "pivot_price": 87.4,
        "signals": {
            "ema_pullback": {
                "strategy": "ema_pullback",
                "entry_trigger": 87.4,
                "inside_day_high": 87.4,
                "inside_day_low": 84.1,
                "surge_move_pct": 0.11,
                "surge_days": 3,
                "surge_volume_ratio": 2.1,
                "days_since_surge": 4,
                "quality_score": 64.0,
            },
        },
        "entry_price": 87.4,
        "stop_price": 81.0,
        "target_price": 101.0,
        "risk_reward": 2.1,
        "rs_rank": 67.0,
        "eps_qoq": 0.08,
        "eps_yoy": -0.04,
        "revenue_qoq": 0.06,
        "revenue_yoy": 0.03,
        "sales_qoq": None,
        "earnings_days_out": 33,
        "wsb_mentions": None,
        "daytrading_mentions": None,
        "insider_buy_days_ago": 21,
        "news_sentiment": 0.22,
        "google_trends_chg": -0.05,
        "pattern_notes": "3-day surge +11% · Pulled back to 5 EMA · Inside day",
        "_seed": 61,
        "_price": 85.0,
        "_trends_keyword": "Ericsson",
    },
    {
        "symbol": "META",
        "exchange": "NASDAQ",
        "currency": "USD",
        "composite_score": 71.0,
        "alert_type": "Pocket Pivot",
        "strategies_fired": ["pocket_pivot"],
        "pivot_price": 612.0,
        "signals": {
            "pocket_pivot": {
                "strategy": "pocket_pivot",
                "reference_sma": "sma_10",
                "reference_sma_value": 598.0,
                "crosses_over": True,
                "volume_ratio_vs_down_days": 1.7,
                "max_down_day_volume": 8_200_000,
                "today_volume": 13_940_000,
                "quality_score": 71.0,
            },
        },
        "entry_price": 612.0,
        "stop_price": 584.0,
        "target_price": 672.0,
        "risk_reward": 2.1,
        "rs_rank": 78.0,
        "eps_qoq": 0.27,
        "eps_yoy": 0.35,
        "revenue_qoq": 0.19,
        "revenue_yoy": 0.27,
        "sales_qoq": None,
        "earnings_days_out": 41,
        "wsb_mentions": 748,
        "daytrading_mentions": 183,
        "insider_buy_days_ago": None,
        "news_sentiment": 0.48,
        "google_trends_chg": 0.18,
        "pattern_notes": "Crosses SMA 10 · Vol ×1.7 vs ↓days · Above SMA 50",
        "_seed": 67,
        "_price": 608.0,
        "_trends_keyword": "Meta stock",
    },
    {
        "symbol": "SAND",
        "exchange": "STO",
        "currency": "SEK",
        "composite_score": 60.0,
        "alert_type": "VCP Setup",
        "strategies_fired": ["vcp"],
        "pivot_price": 224.0,
        "signals": {
            "vcp": {
                "strategy": "vcp",
                "pivot_price": 224.0,
                "n_contractions": 2,
                "contraction_depths": [0.10, 0.06],
                "volume_declining": False,
                "quality_score": 60.0,
            },
        },
        "entry_price": 224.0,
        "stop_price": 208.0,
        "target_price": 256.0,
        "risk_reward": 2.0,
        "rs_rank": 61.0,
        "eps_qoq": 0.14,
        "eps_yoy": 0.21,
        "revenue_qoq": 0.09,
        "revenue_yoy": 0.15,
        "sales_qoq": 0.11,
        "earnings_days_out": 58,
        "wsb_mentions": None,
        "daytrading_mentions": None,
        "insider_buy_days_ago": None,
        "news_sentiment": 0.14,
        "google_trends_chg": None,
        "pattern_notes": "2 contractions · Vol mixed · Near 52w high",
        "_seed": 79,
        "_price": 220.0,
        "_trends_keyword": "Sandvik",
    },
]
